"""Factory for generating test wallets."""

from typing import Optional

from rfq_test.crypto.wallet import Wallet, generate_wallets_from_seed


class WalletFactory:
    """Factory for creating test wallets.
    
    Supports both random generation and deterministic
    generation from seed phrase.
    """
    
    def __init__(
        self,
        seed_phrase: Optional[str] = None,
        start_index: int = 0,
    ):
        """Initialize wallet factory.
        
        Args:
            seed_phrase: Optional seed for deterministic generation
            start_index: Starting index for HD derivation
        """
        self.seed_phrase = seed_phrase
        self._current_index = start_index
        self._generated_wallets: list[Wallet] = []
    
    def create(self) -> Wallet:
        """Create a single wallet.
        
        Uses seed phrase if available and valid, otherwise random.
        
        Returns:
            New wallet
        """
        if self.seed_phrase and self._is_valid_seed_phrase(self.seed_phrase):
            try:
                wallets = generate_wallets_from_seed(
                    self.seed_phrase,
                    count=1,
                    start_index=self._current_index,
                )
                self._current_index += 1
                wallet = wallets[0]
            except Exception:
                # Fall back to random if seed phrase fails
                wallet = Wallet.generate()
        else:
            wallet = Wallet.generate()
        
        self._generated_wallets.append(wallet)
        return wallet
    
    def _is_valid_seed_phrase(self, phrase: str) -> bool:
        """Check if seed phrase looks valid (not a placeholder)."""
        if not phrase:
            return False
        words = phrase.strip().split()
        # Check it has 12 or 24 words and doesn't look like placeholder
        if len(words) not in (12, 24):
            return False
        # Check for obvious placeholder patterns
        if any(w.startswith("word") for w in words):
            return False
        return True
    
    def create_many(self, count: int) -> list[Wallet]:
        """Create multiple wallets.
        
        Args:
            count: Number of wallets to create
            
        Returns:
            List of wallets
        """
        if self.seed_phrase and self._is_valid_seed_phrase(self.seed_phrase):
            try:
                wallets = generate_wallets_from_seed(
                    self.seed_phrase,
                    count=count,
                    start_index=self._current_index,
                )
                self._current_index += count
                self._generated_wallets.extend(wallets)
                return wallets
            except Exception:
                # Fall back to random
                return [self.create() for _ in range(count)]
        else:
            return [self.create() for _ in range(count)]
    
    def get_all_generated(self) -> list[Wallet]:
        """Get all wallets generated by this factory.
        
        Returns:
            List of generated wallets
        """
        return self._generated_wallets.copy()
    
    def reset(self, start_index: int = 0) -> None:
        """Reset the factory.
        
        Args:
            start_index: New starting index
        """
        self._current_index = start_index
        self._generated_wallets.clear()
